# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageWidget.sizePolicy().hasHeightForWidth())
        self.imageWidget.setSizePolicy(sizePolicy)
        self.imageWidget.setObjectName("imageWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.imageWidget)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imageLayout = QtWidgets.QHBoxLayout()
        self.imageLayout.setObjectName("imageLayout")
        self.horizontalLayout_2.addLayout(self.imageLayout)
        self.verticalLayout.addWidget(self.imageWidget)
        self.textWidget = QtWidgets.QWidget(self.centralwidget)
        self.textWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.textWidget.setObjectName("textWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.textWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.infoWidget = QtWidgets.QWidget(self.textWidget)
        self.infoWidget.setObjectName("infoWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.infoWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.infoLabel = QtWidgets.QLabel(self.infoWidget)
        self.infoLabel.setLineWidth(1)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout_2.addWidget(self.infoLabel)
        self.horizontalLayout.addWidget(self.infoWidget)
        self.frame = QtWidgets.QFrame(self.textWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 15, 110, 24))
        self.label.setObjectName("label")
        self.spinBox_blocksize = QtWidgets.QSpinBox(self.frame)
        self.spinBox_blocksize.setGeometry(QtCore.QRect(140, 15, 60, 30))
        self.spinBox_blocksize.setMinimum(1)
        self.spinBox_blocksize.setSingleStep(2)
        self.spinBox_blocksize.setProperty("value", 15)
        self.spinBox_blocksize.setObjectName("spinBox_blocksize")
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.textWidget)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 60))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_exec = QtWidgets.QPushButton(self.widget)
        self.pushButton_exec.setObjectName("pushButton_exec")
        self.horizontalLayout_3.addWidget(self.pushButton_exec)
        self.pushButton_save = QtWidgets.QPushButton(self.widget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_3.addWidget(self.pushButton_save)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.infoLabel.setText(_translate("MainWindow", "file:"))
        self.label.setText(_translate("MainWindow", "block size"))
        self.pushButton_exec.setText(_translate("MainWindow", "適用"))
        self.pushButton_save.setText(_translate("MainWindow", "保存"))

